package life.cj.community.community.mapper;

import java.util.List;
import life.cj.community.community.model.Users;
import life.cj.community.community.model.UsersExample;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    int insert(Users row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    int insertSelective(Users row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    int updateByExampleSelective(@Param("row") Users row, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.USERS
     *
     * @mbg.generated Thu Nov 03 09:48:35 CST 2022
     */
    int updateByExample(@Param("row") Users row, @Param("example") UsersExample example);
}